#!/bin/sh

### BEGIN INIT INFO
# Provides:          hubic
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Should-Start:
# Should-Stop:
# Short-Description: start hubic client
### END INIT INFO

PIDDIR=/var/run
HUBICPID=$PIDDIR/hubic.pid
USER=hubic

# clear conflicting settings from the environment
unset TMPDIR

case "$1" in
        start)
                su - $USER -c "hubic start && echo $!"
                pgrep -u $USER mono > $HUBICPID

                ;;
        stop)
                su - $USER -c "hubic stop"
                rm -f $NMBDPID

                ;;
        status)
                su - $USER -c "hubic status"
                ;;
        *)
                echo "Usage: /etc/init.d/hubic {start|stop|status}"
                exit 1
                ;;
esac

exit 0
